DEV-2330 split of AdjustableCurrentController
futurehomeno/cliffhanger pull request #91
Opened 2023-11-03 12:49 UTC by EdytaMalcharek

2023-11-03 16:55 UTC, rafalmnich requested changes
Pls also rebase / merge with main branch, to resolve conflicts.

2023-11-03 16:55 UTC, rafalmnich commented on adapter/service/chargepoint/service.go
> +		return nil, fmt.Errorf("%s: adjusting current is not supported", s.Name())
Adjust error strings according to property names.

2023-11-03 16:55 UTC, rafalmnich commented on adapter/service/chargepoint/service.go
>  	_, ok := s.Specification().PropertyInteger(PropertySupportedMaxCurrent)
`PropertyOfferedCurrent` ?

2023-11-06 08:01 UTC, rafalmnich approved these changes

2023-11-06 08:03 UTC, rafalmnich requested changes

2023-11-06 08:03 UTC, rafalmnich commented on adapter/service/chargepoint/tasks.go
> +<<<<<<< HEAD
You haven't finished resolving the conflicts, as the conflicts markers are still here.

2023-11-06 13:34 UTC, rafalmnich requested changes

2023-11-06 13:34 UTC, rafalmnich commented on adapter/service/chargepoint/service.go
> +	SupportsAdjustingMaxCurrent() bool
I think that it should check if supports offered current, and maybe in addition - the max current. @boguslaw-wojcik what do you think?

```suggestion
	// SupportsAdjustingOfferedCurrent returns true if the chargepoint supports adjusting offered current.
	SupportsAdjustingOfferedCurrent() bool
```

2023-11-06 14:08 UTC, boguslaw-wojcik commented on adapter/service/chargepoint/service.go
> +	_, ok := s.Specification().PropertyInteger(PropertyOfferedCurrent)
Nope, this is incorrect. PropertyOfferedCurrent is a property of "evt.current_session.report" interface, not a service specification.

What you should check here, is if there is sup_max_current property defining an upper boundary for setting offered current.

2023-11-06 14:09 UTC, boguslaw-wojcik submitted a review, later dismissed
As per left comments.

2023-11-06 14:13 UTC, boguslaw-wojcik commented on adapter/service/chargepoint/service.go
> +	_, ok := s.Specification().PropertyInteger(PropertyOfferedCurrent)
The logic dictates we have this requirement for both of the controllers.

2023-11-08 10:55 UTC, boguslaw-wojcik commented on adapter/service/chargepoint/service.go
>  	_, ok := s.Specification().PropertyInteger(PropertySupportedMaxCurrent)
Nope.

2023-11-10 11:58 UTC, boguslaw-wojcik approved these changes

2023-11-10 12:33 UTC, merged